/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;
import CLASSES.Comptable;
import CLASSES.Demandeur;
import CLASSES.IndiceReleve;
import CLASSES.Session;
import CONNEXION.Connexion;
import javax.swing.JOptionPane;

/**
 *
 * @author shindano
 */
public class gestionItrefacesEnregistrements extends javax.swing.JFrame {

    /**
     * Creates new form gestionItrefacesEnregistrements
     */
    Comptable cmpt=new Comptable();
    Demandeur dem= new Demandeur();
    IndiceReleve idr= new IndiceReleve();
    Session sess= new Session();
    public gestionItrefacesEnregistrements() {
      
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false);
          Releve.setSelectedIndex(4);
          comboMat();
          comboDemandeur();
          comboSession();
    }
      Connexion cnx= new Connexion();
   
     public void comboMat() {
        try {
           ComboBoxDemandeurComptable.removeAllItems();
            String req = "select matricule from comptable ";
            cnx.selection(req);
            
            while (cnx.Rs.next()) {
                String nom = cnx.Rs.getString("matricule");
               ComboBoxDemandeurComptable.addItem(nom);
            }
        } catch (Exception e) {
            System.out.println("Erreur : " + e.getMessage());
        }
    }
     public void comboDemandeur() {
        try {
           ComboBoxReleveDemandeur.removeAllItems();
            String req = "select numeroId from demandeur ";
            cnx.selection(req);
            
            while (cnx.Rs.next()) {
                String nom = cnx.Rs.getString("numeroId");
               ComboBoxReleveDemandeur.addItem(nom);
            }
        } catch (Exception e) {
            System.out.println("Erreur : " + e.getMessage());
        }
    }
     public void comboSession() {
        try {
           ComboBoxReleveSession.removeAllItems();
            String req = "select indiceAnnee from sesssion ";
            cnx.selection(req);
            
            while (cnx.Rs.next()) {
                String nom = cnx.Rs.getString("indiceAnnee");
               ComboBoxReleveSession.addItem(nom);
            }
        } catch (Exception e) {
            System.out.println("Erreur : " + e.getMessage());
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void nettoyerCompt(){
       TextfieldComptableMatricule.setText("");
        TextfieldComptableNom.setText("");
     TextfieldComptablePostnom.setText("");
       TextfieldComptablePrenom.setText("");
        TextfieldComptableSexe.setText("");
    }
    private void nettoyerDem(){
       TextFieldDemandeurNumeroId.setText("");
       TextFieldDemandeurNom.setText("");
       TextFieldDemandeurPostnom.setText("");
       TextFieldDemandeurPrenom.setText("");
       TextFieldDemandeurSexe.setText("");
       TextFieldDemandeurStatut.setText("");
       TextFieldDemandeurDate.setText("");
        ComboBoxDemandeurComptable.setSelectedIndex(-1);
    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Releve = new javax.swing.JTabbedPane();
        EnregistrerComptable = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TextfieldComptableMatricule = new javax.swing.JTextField();
        TextfieldComptableSexe = new javax.swing.JTextField();
        TextfieldComptableNom = new javax.swing.JTextField();
        TextfieldComptablePostnom = new javax.swing.JTextField();
        TextfieldComptablePrenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonEnregistrerComptable = new javax.swing.JButton();
        jButtonEnregistrerComptable1 = new javax.swing.JButton();
        EnregistrerDemandeur = new javax.swing.JPanel();
        EnregistrerDem = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TextFieldDemandeurNumeroId = new javax.swing.JTextField();
        TextFieldDemandeurSexe = new javax.swing.JTextField();
        TextFieldDemandeurNom = new javax.swing.JTextField();
        TextFieldDemandeurPostnom = new javax.swing.JTextField();
        TextFieldDemandeurPrenom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ButtonEnregistrerDemandeur = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TextFieldDemandeurStatut = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TextFieldDemandeurDate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ComboBoxDemandeurComptable = new javax.swing.JComboBox<>();
        ButtonEnregistrerDemandeur1 = new javax.swing.JButton();
        AjoutSession = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        TextFieldSessionIndice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TextFieldSessionLibelle = new javax.swing.JTextField();
        ButtonAjouterSession = new javax.swing.JButton();
        ButtonAjouterSession1 = new javax.swing.JButton();
        ReleveIndice = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        ComboBoxReleveDemandeur = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        ComboBoxReleveSession = new javax.swing.JComboBox<>();
        ButtonAjouterReleve = new javax.swing.JButton();
        ButtonAjouterReleve1 = new javax.swing.JButton();
        ChoixEnregistrement = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CAS D'ENREGISTREMENT");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("COMPTABLE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("AJOUT INDICE RELEVES");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("DEMANDEUR");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("AJOUT SESSION");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/retour.PNG"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Releve.setBackground(new java.awt.Color(255, 255, 255));

        EnregistrerComptable.setBackground(new java.awt.Color(255, 255, 255));
        EnregistrerComptable.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setText("Sexe");

        TextfieldComptableMatricule.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextfieldComptableMatricule.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));

        TextfieldComptableSexe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextfieldComptableSexe.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        TextfieldComptableSexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldComptableSexeActionPerformed(evt);
            }
        });

        TextfieldComptableNom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextfieldComptableNom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));

        TextfieldComptablePostnom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextfieldComptablePostnom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));

        TextfieldComptablePrenom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextfieldComptablePrenom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        TextfieldComptablePrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldComptablePrenomActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setText("Nom");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setText("Matricule");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setText("Prénom");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel6.setText("Postnom");

        jButtonEnregistrerComptable.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEnregistrerComptable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonEnregistrerComptable.setText("ENREGISTRER");
        jButtonEnregistrerComptable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        jButtonEnregistrerComptable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerComptableActionPerformed(evt);
            }
        });

        jButtonEnregistrerComptable1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEnregistrerComptable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonEnregistrerComptable1.setText("FERMER");
        jButtonEnregistrerComptable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        jButtonEnregistrerComptable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerComptable1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnregistrerComptableLayout = new javax.swing.GroupLayout(EnregistrerComptable);
        EnregistrerComptable.setLayout(EnregistrerComptableLayout);
        EnregistrerComptableLayout.setHorizontalGroup(
            EnregistrerComptableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnregistrerComptableLayout.createSequentialGroup()
                .addGroup(EnregistrerComptableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EnregistrerComptableLayout.createSequentialGroup()
                        .addGap(0, 387, Short.MAX_VALUE)
                        .addComponent(TextfieldComptableMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EnregistrerComptableLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(EnregistrerComptableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EnregistrerComptableLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextfieldComptableSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EnregistrerComptableLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextfieldComptablePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EnregistrerComptableLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextfieldComptableNom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EnregistrerComptableLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextfieldComptablePostnom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EnregistrerComptableLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(EnregistrerComptableLayout.createSequentialGroup()
                                .addComponent(jButtonEnregistrerComptable, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEnregistrerComptable1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(109, 109, 109))
        );
        EnregistrerComptableLayout.setVerticalGroup(
            EnregistrerComptableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnregistrerComptableLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(EnregistrerComptableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextfieldComptableMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(EnregistrerComptableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextfieldComptableNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(EnregistrerComptableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextfieldComptablePostnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(EnregistrerComptableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextfieldComptablePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(EnregistrerComptableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextfieldComptableSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(EnregistrerComptableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnregistrerComptable, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnregistrerComptable1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        Releve.addTab("tab1", EnregistrerComptable);

        EnregistrerDemandeur.setBackground(new java.awt.Color(255, 255, 255));

        EnregistrerDem.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel7.setText("Statut");

        TextFieldDemandeurNumeroId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextFieldDemandeurNumeroId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));

        TextFieldDemandeurSexe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextFieldDemandeurSexe.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        TextFieldDemandeurSexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDemandeurSexeActionPerformed(evt);
            }
        });

        TextFieldDemandeurNom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextFieldDemandeurNom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));

        TextFieldDemandeurPostnom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextFieldDemandeurPostnom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));

        TextFieldDemandeurPrenom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextFieldDemandeurPrenom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel8.setText("Nom");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel9.setText("Numero Id");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel10.setText("Prénom");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel11.setText("Postnom");

        ButtonEnregistrerDemandeur.setBackground(new java.awt.Color(255, 255, 255));
        ButtonEnregistrerDemandeur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ButtonEnregistrerDemandeur.setText("ENREGISTRER");
        ButtonEnregistrerDemandeur.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        ButtonEnregistrerDemandeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnregistrerDemandeurActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel12.setText("Sexe");

        TextFieldDemandeurStatut.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextFieldDemandeurStatut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        TextFieldDemandeurStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDemandeurStatutActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel13.setText("Date");

        TextFieldDemandeurDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TextFieldDemandeurDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        TextFieldDemandeurDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDemandeurDateActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel14.setText("Matricule Comptable");

        ComboBoxDemandeurComptable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ComboBoxDemandeurComptable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Comptable" }));
        ComboBoxDemandeurComptable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 102, 255)));

        ButtonEnregistrerDemandeur1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonEnregistrerDemandeur1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ButtonEnregistrerDemandeur1.setText("FERMER");
        ButtonEnregistrerDemandeur1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        ButtonEnregistrerDemandeur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnregistrerDemandeur1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnregistrerDemLayout = new javax.swing.GroupLayout(EnregistrerDem);
        EnregistrerDem.setLayout(EnregistrerDemLayout);
        EnregistrerDemLayout.setHorizontalGroup(
            EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnregistrerDemLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnregistrerDemLayout.createSequentialGroup()
                        .addComponent(ButtonEnregistrerDemandeur, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonEnregistrerDemandeur1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnregistrerDemLayout.createSequentialGroup()
                        .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11)
                            .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldDemandeurPostnom)
                            .addComponent(TextFieldDemandeurPrenom)
                            .addComponent(TextFieldDemandeurNom)
                            .addComponent(TextFieldDemandeurSexe)
                            .addComponent(TextFieldDemandeurNumeroId)
                            .addComponent(TextFieldDemandeurStatut)
                            .addComponent(TextFieldDemandeurDate)
                            .addComponent(ComboBoxDemandeurComptable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(147, 147, 147))
        );
        EnregistrerDemLayout.setVerticalGroup(
            EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnregistrerDemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldDemandeurNumeroId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TextFieldDemandeurNom, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldDemandeurPostnom, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldDemandeurPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EnregistrerDemLayout.createSequentialGroup()
                        .addComponent(TextFieldDemandeurStatut, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(ComboBoxDemandeurComptable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnregistrerDemLayout.createSequentialGroup()
                        .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TextFieldDemandeurSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22)
                        .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TextFieldDemandeurDate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(EnregistrerDemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonEnregistrerDemandeur, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEnregistrerDemandeur1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout EnregistrerDemandeurLayout = new javax.swing.GroupLayout(EnregistrerDemandeur);
        EnregistrerDemandeur.setLayout(EnregistrerDemandeurLayout);
        EnregistrerDemandeurLayout.setHorizontalGroup(
            EnregistrerDemandeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
            .addGroup(EnregistrerDemandeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnregistrerDemandeurLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EnregistrerDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        EnregistrerDemandeurLayout.setVerticalGroup(
            EnregistrerDemandeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
            .addGroup(EnregistrerDemandeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnregistrerDemandeurLayout.createSequentialGroup()
                    .addContainerGap(115, Short.MAX_VALUE)
                    .addComponent(EnregistrerDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        Releve.addTab("tab2", EnregistrerDemandeur);

        AjoutSession.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Indice Année");

        TextFieldSessionIndice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Libellé");

        TextFieldSessionLibelle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));

        ButtonAjouterSession.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAjouterSession.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ButtonAjouterSession.setText("FERMER");
        ButtonAjouterSession.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        ButtonAjouterSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjouterSessionActionPerformed(evt);
            }
        });

        ButtonAjouterSession1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAjouterSession1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ButtonAjouterSession1.setText("AJOUTER");
        ButtonAjouterSession1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        ButtonAjouterSession1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjouterSession1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AjoutSessionLayout = new javax.swing.GroupLayout(AjoutSession);
        AjoutSession.setLayout(AjoutSessionLayout);
        AjoutSessionLayout.setHorizontalGroup(
            AjoutSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AjoutSessionLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(AjoutSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AjoutSessionLayout.createSequentialGroup()
                        .addComponent(ButtonAjouterSession1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAjouterSession, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AjoutSessionLayout.createSequentialGroup()
                        .addGroup(AjoutSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addGroup(AjoutSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldSessionLibelle)
                            .addComponent(TextFieldSessionIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(131, 131, 131))
        );
        AjoutSessionLayout.setVerticalGroup(
            AjoutSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjoutSessionLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(AjoutSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSessionIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(AjoutSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSessionLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(80, 80, 80)
                .addGroup(AjoutSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAjouterSession, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAjouterSession1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(258, Short.MAX_VALUE))
        );

        Releve.addTab("tab3", AjoutSession);

        ReleveIndice.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Numéro demandeur");

        ComboBoxReleveDemandeur.setSelectedItem("CHOISISSEZ");
        ComboBoxReleveDemandeur.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 102, 255)));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Indice Session");

        ComboBoxReleveSession.setSelectedItem("CHOISISSEZ");
        ComboBoxReleveSession.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 102, 255)));

        ButtonAjouterReleve.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAjouterReleve.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ButtonAjouterReleve.setText("AJOUTER");
        ButtonAjouterReleve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        ButtonAjouterReleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjouterReleveActionPerformed(evt);
            }
        });

        ButtonAjouterReleve1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAjouterReleve1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ButtonAjouterReleve1.setText("FERMER");
        ButtonAjouterReleve1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));
        ButtonAjouterReleve1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjouterReleve1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReleveIndiceLayout = new javax.swing.GroupLayout(ReleveIndice);
        ReleveIndice.setLayout(ReleveIndiceLayout);
        ReleveIndiceLayout.setHorizontalGroup(
            ReleveIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReleveIndiceLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(ReleveIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReleveIndiceLayout.createSequentialGroup()
                        .addComponent(ButtonAjouterReleve, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAjouterReleve1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReleveIndiceLayout.createSequentialGroup()
                        .addGroup(ReleveIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(118, 118, 118)
                        .addGroup(ReleveIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxReleveDemandeur, 0, 161, Short.MAX_VALUE)
                            .addComponent(ComboBoxReleveSession, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(121, 121, 121))
        );
        ReleveIndiceLayout.setVerticalGroup(
            ReleveIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReleveIndiceLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(ReleveIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxReleveDemandeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ReleveIndiceLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17)))
                .addGap(48, 48, 48)
                .addGroup(ReleveIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ComboBoxReleveSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addGroup(ReleveIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAjouterReleve, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAjouterReleve1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );

        Releve.addTab("tab4", ReleveIndice);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("MENU CHOIX");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel20)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jLabel19.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel19.setText("CHOISISSEZ CE QUE VOUS VOULEZ FAIRE A GAUCHE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel19)
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel19)
                .addGap(0, 287, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(379, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );

        javax.swing.GroupLayout ChoixEnregistrementLayout = new javax.swing.GroupLayout(ChoixEnregistrement);
        ChoixEnregistrement.setLayout(ChoixEnregistrementLayout);
        ChoixEnregistrementLayout.setHorizontalGroup(
            ChoixEnregistrementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ChoixEnregistrementLayout.setVerticalGroup(
            ChoixEnregistrementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoixEnregistrementLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Releve.addTab("tab5", ChoixEnregistrement);

        getContentPane().add(Releve, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, -41, -1, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextfieldComptableSexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldComptableSexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldComptableSexeActionPerformed

    private void TextFieldDemandeurSexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDemandeurSexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDemandeurSexeActionPerformed

    private void ButtonEnregistrerDemandeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnregistrerDemandeurActionPerformed
        // TODO add your handling code here:
         if (TextFieldDemandeurNumeroId.getText().compareTo("") == 0 || TextFieldDemandeurNom.getText().compareTo("") == 0 || TextFieldDemandeurPostnom.getText().compareTo("") == 0 || TextFieldDemandeurPrenom.getText().compareTo("") == 0|| TextFieldDemandeurSexe.getText().compareTo("") == 0||TextFieldDemandeurStatut.getText().compareTo("") == 0|| TextFieldDemandeurDate.getText().compareTo("") == 0||ComboBoxDemandeurComptable.getSelectedIndex()<0) {
            JOptionPane.showMessageDialog(null, "REMPLISSEZ TOUS LES CHAMPS SVP!!!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
        }
         else{
        dem.setNumeroId(TextFieldDemandeurNumeroId.getText());
        dem.setNomDem(TextFieldDemandeurNom.getText());
        dem.setPostnomDem(TextFieldDemandeurPostnom.getText());
        dem.setPrenomDem(TextFieldDemandeurPrenom.getText());
        dem.setSexeDem(TextFieldDemandeurSexe.getText());
        dem.setStatutDem(TextFieldDemandeurStatut.getText());
        dem.setDateDem(TextFieldDemandeurDate.getText());
        dem.setComptableReference(ComboBoxDemandeurComptable.getSelectedItem().toString());
        dem.AjouterDemandeur();
        nettoyerDem();
        JOptionPane.showConfirmDialog(null, "SUCCESS", "CONFIRMATION", JOptionPane.PLAIN_MESSAGE);
         }
    }//GEN-LAST:event_ButtonEnregistrerDemandeurActionPerformed

    private void TextFieldDemandeurStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDemandeurStatutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDemandeurStatutActionPerformed

    private void TextFieldDemandeurDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDemandeurDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDemandeurDateActionPerformed

    private void ButtonAjouterSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjouterSessionActionPerformed
        // TODO add your handling code here:
         Releve.setSelectedIndex(4);
    }//GEN-LAST:event_ButtonAjouterSessionActionPerformed

    private void ButtonAjouterReleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjouterReleveActionPerformed
        // TODO add your handling code here:
        if (ComboBoxReleveDemandeur.getSelectedIndex()<0||ComboBoxReleveSession.getSelectedIndex()<0) {
             JOptionPane.showMessageDialog(null, "SELECTIONNEZ UN DEMANDEUR ET UNE SESSION SVP!!!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
        }
        else{
        
        idr.setDemandeReleve(ComboBoxReleveDemandeur.getSelectedItem().toString());
        idr.setSessionReleve(ComboBoxReleveSession.getSelectedItem().toString());
        idr.AjouterIndiceReleve();
        ComboBoxReleveDemandeur.setSelectedIndex(-1);
        ComboBoxReleveSession.setSelectedIndex(-1);
         JOptionPane.showConfirmDialog(null, "SUCCESS", "CONFIRMATION", JOptionPane.PLAIN_MESSAGE);
        }
        
    }//GEN-LAST:event_ButtonAjouterReleveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Releve.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Releve.setSelectedIndex(1);
          comboMat();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         Releve.setSelectedIndex(2);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        comboDemandeur();
          comboSession();
         Releve.setSelectedIndex(3);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonEnregistrerComptableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerComptableActionPerformed
        // TODO add your handling code here:
        if (TextfieldComptableMatricule.getText().compareTo("")==00||TextfieldComptableNom.getText().compareTo("")==0||TextfieldComptablePostnom.getText().compareTo("")==0||TextfieldComptablePrenom.getText().compareTo("")==0||TextfieldComptableSexe.getText().compareTo("")==0) {
             JOptionPane.showMessageDialog(null, "REMPLISSEZ TOUS LES CHAMPS SVP!!!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
        }
        else{
        cmpt.setMatricule(TextfieldComptableMatricule.getText());
        cmpt.setNomCompt(TextfieldComptableNom.getText());
        cmpt.setPostnomComt(TextfieldComptablePostnom.getText());
        cmpt.setPrenomCompt(TextfieldComptablePrenom.getText());
        cmpt.setSexeCompte(TextfieldComptableSexe.getText());
        cmpt.AjouterComptable();
        nettoyerCompt();
        JOptionPane.showConfirmDialog(null, "SUCCESS", "CONFIRMATION", JOptionPane.PLAIN_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonEnregistrerComptableActionPerformed

    private void ButtonAjouterReleve1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjouterReleve1ActionPerformed
        // TODO add your handling code here:
         Releve.setSelectedIndex(4);
    }//GEN-LAST:event_ButtonAjouterReleve1ActionPerformed

    private void ButtonAjouterSession1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjouterSession1ActionPerformed
        // TODO add your handling code here:
        if (TextFieldSessionIndice.getText().compareTo("")==0||TextFieldSessionLibelle.getText().compareTo("")==0) {
             JOptionPane.showMessageDialog(null, "METTEZ L'INDICE DE LA SESSION SVP ET REESSAYEZ!!!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
        }
        else{
       sess.setIndiceAnnee(TextFieldSessionIndice.getText());
       sess.setLibelle(TextFieldSessionLibelle.getText());
        TextFieldSessionIndice.setText("");
        TextFieldSessionLibelle.setText("");
        sess.AjouterSession();
        JOptionPane.showConfirmDialog(null, "LA SESSION A ETE AJOUTER", "CONFIRMATION", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_ButtonAjouterSession1ActionPerformed

    private void ButtonEnregistrerDemandeur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnregistrerDemandeur1ActionPerformed
        // TODO add your handling code here:
         Releve.setSelectedIndex(4);
    }//GEN-LAST:event_ButtonEnregistrerDemandeur1ActionPerformed

    private void jButtonEnregistrerComptable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerComptable1ActionPerformed
        // TODO add your handling code here:
         Releve.setSelectedIndex(4);
    }//GEN-LAST:event_jButtonEnregistrerComptable1ActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
         MenuPrincipal mi= new MenuPrincipal();
        mi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void TextfieldComptablePrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldComptablePrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldComptablePrenomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionItrefacesEnregistrements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionItrefacesEnregistrements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionItrefacesEnregistrements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionItrefacesEnregistrements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionItrefacesEnregistrements().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AjoutSession;
    private javax.swing.JButton ButtonAjouterReleve;
    private javax.swing.JButton ButtonAjouterReleve1;
    private javax.swing.JButton ButtonAjouterSession;
    private javax.swing.JButton ButtonAjouterSession1;
    private javax.swing.JButton ButtonEnregistrerDemandeur;
    private javax.swing.JButton ButtonEnregistrerDemandeur1;
    private javax.swing.JPanel ChoixEnregistrement;
    private javax.swing.JComboBox<String> ComboBoxDemandeurComptable;
    private javax.swing.JComboBox<String> ComboBoxReleveDemandeur;
    private javax.swing.JComboBox<String> ComboBoxReleveSession;
    private javax.swing.JPanel EnregistrerComptable;
    private javax.swing.JPanel EnregistrerDem;
    private javax.swing.JPanel EnregistrerDemandeur;
    private javax.swing.JTabbedPane Releve;
    private javax.swing.JPanel ReleveIndice;
    private javax.swing.JTextField TextFieldDemandeurDate;
    private javax.swing.JTextField TextFieldDemandeurNom;
    private javax.swing.JTextField TextFieldDemandeurNumeroId;
    private javax.swing.JTextField TextFieldDemandeurPostnom;
    private javax.swing.JTextField TextFieldDemandeurPrenom;
    private javax.swing.JTextField TextFieldDemandeurSexe;
    private javax.swing.JTextField TextFieldDemandeurStatut;
    private javax.swing.JTextField TextFieldSessionIndice;
    private javax.swing.JTextField TextFieldSessionLibelle;
    private javax.swing.JTextField TextfieldComptableMatricule;
    private javax.swing.JTextField TextfieldComptableNom;
    private javax.swing.JTextField TextfieldComptablePostnom;
    private javax.swing.JTextField TextfieldComptablePrenom;
    private javax.swing.JTextField TextfieldComptableSexe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonEnregistrerComptable;
    private javax.swing.JButton jButtonEnregistrerComptable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
